name: Deploy UI to Railway

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Build
        run: npm run build

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh || {
            echo "Fallback install..."
            curl -L https://github.com/railwayapp/cli/releases/latest/download/railway-linux-x86_64.tar.gz -o railway.tar.gz
            tar -xzf railway.tar.gz
            sudo mv railway /usr/local/bin/
            chmod +x /usr/local/bin/railway
          }
          if [ -d "$HOME/.railway/bin" ]; then
            echo "$HOME/.railway/bin" >> $GITHUB_PATH
            export PATH="$HOME/.railway/bin:$PATH"
          fi
          railway --version || railway version || true

      - name: Deploy to Railway (autopartes-ui)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --service "autopartes-ui" || railway up
